jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go vet ./...
      - run: |
          cd cmd/waitport
          env GOOS=darwin go build -o waitport-darwin
          env GOOS=linux go build -o waitport-linux
          ls -la
          cd ../..
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: cmd/waitport
          paths: "waitport-*"
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: ./bin
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git describe $(git rev-list --tags --max-count=1))
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/