jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go vet ./...
      - run: |
          cd cmd/waitport
          go build
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
